Kintal_Detanl/Models/DrugViewModel.cs
using Microsoft.Ajax.Utilities;
using MspCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Kintal_Detanl.Models
{
    public class DrugViewModel
    {
        #region Properties
        public long Id { get; set; }
        public string DrugName { get; set; }
        public string GenericName { get; set; }
        public string Description { get; set; }
        #endregion

        #region Drug data layer
        public static DrugViewModel InsertOrUpdateDrugDetails(string conString, DrugViewModel drugModel)
        {
            using (SqlConnection cn = new SqlConnection(conString))
            {
                cn.Open();
                SqlCommand cmd = new SqlCommand("wp_sp_InsertUpdateDrugMaster", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(drugModel.Id));
                cmd.Parameters.AddWithValue("@DrugName", SqlUtils.SetDbConformValueString(drugModel.DrugName));
                cmd.Parameters.AddWithValue("@GenericName", SqlUtils.SetDbConformValueString(drugModel.GenericName));
                cmd.Parameters.AddWithValue("@Description", SqlUtils.SetDbConformValueString(drugModel.Description));

                SqlParameter outputParamReturnedValue = cmd.Parameters.Add("@ReturnValue", SqlDbType.Int);
                outputParamReturnedValue.Direction = ParameterDirection.Output;
                cmd.ExecuteNonQuery();
                drugModel.Id = !string.IsNullOrWhiteSpace(cmd.Parameters["@ReturnValue"].Value.ToString()) ? Convert.ToInt32(cmd.Parameters["@ReturnValue"].Value) : 0;
                cn.Close();
                return drugModel;
            }
        }
        public static List<DrugViewModel> GetDrugs(string conString)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getDrugMasterList";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                List<DrugViewModel> res = BindDrugsListFromDataTable(dtblResult);
                return (res != null && res.Count > 0) ? res : new List<DrugViewModel>();
            }
        }
        public static DrugViewModel GetDrugById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getDrugMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                DrugViewModel res = BindDrugFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? res : new DrugViewModel();
            }
        }
        public static bool DeleteDrugById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_DeleteDrugMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                DrugViewModel res = BindDrugFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? true : false;
            }
        }
        #endregion

        #region Data Access
        private static List<DrugViewModel> BindDrugsListFromDataTable(DataTable dtDrug)
        {
            List<DrugViewModel> drugList = null;

            if (dtDrug != null && dtDrug.Rows.Count > 0)
            {
                drugList = new List<DrugViewModel>();
                using (DataTableReader dataTableReader = new DataTableReader(dtDrug))
                {
                    while (dataTableReader.Read())
                    {
                        DrugViewModel drugModel = new DrugViewModel();
                        LoadDrugObjectDataFromDataTableReader(dataTableReader, drugModel);
                        drugList.Add(drugModel);
                    }
                }
            }

            return drugList;
        }
        private static DrugViewModel BindDrugFromDataTable(DataTable dtDrug)
        {
            DrugViewModel drug = null;
            if (dtDrug != null && dtDrug.Rows.Count > 0)
            {
                drug = new DrugViewModel();
                DataTableReader inputDataTableReader = SqlUtils.CreateReaderMoveToFirstRow(dtDrug);
                LoadDrugObjectDataFromDataTableReader(inputDataTableReader, drug);
            }

            return drug;
        }
        private static void LoadDrugObjectDataFromDataTableReader(DataTableReader inputDataTableReader, DrugViewModel drugModel)
        {
            if (inputDataTableReader != null && inputDataTableReader.HasRows)
            {
                drugModel.Id = SqlUtils.GetInt64("Id", inputDataTableReader);
                drugModel.DrugName = SqlUtils.GetString("DrugName", inputDataTableReader);
                drugModel.GenericName = SqlUtils.GetString("GenericName", inputDataTableReader);
                drugModel.Description = SqlUtils.GetString("Description", inputDataTableReader);
            }
        }
        #endregion
    }
}

Kintal_Detanl/Controllers/DrugController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kintal_Detanl.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Kintal_Detanl.Controllers
{
    public class DrugController : Controller
    {
        #region Connection String Declarations

        private static readonly string _connStringDefault = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        #endregion

        // GET: Drug/Index
        public ActionResult DrugList()
        {
            return View();
        }

        [HttpPost]
        public JsonResult BindDrugList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(DrugViewModel.GetDrugs(_connStringDefault).ToDataSourceResult(request));
        }

        //GET: Drug/DrugDetails/id
        public ActionResult DrugDetails(int id = 0, string mode = "add")
        {
            ViewBag.PageMode = mode;
            var drug = new DrugViewModel();
            if (id > 0)
            {
                drug = DrugViewModel.GetDrugById(_connStringDefault, id);
            }
            return View(drug);
        }

        //POST: Drug/DrugDetails
        [HttpPost]
        public ActionResult DrugDetails(DrugViewModel drugModel)
        {
            try
            {
                var result = new DrugViewModel();
                if (drugModel != null && !string.IsNullOrWhiteSpace(drugModel.DrugName))
                {
                    result = DrugViewModel.InsertOrUpdateDrugDetails(_connStringDefault.ToString(), drugModel);
                }
                return Json(new object[] { true, result });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }

        //DELETE: Drug/id
        [HttpDelete]
        public JsonResult DeleteDrug(int id)
        {
            try
            {
                DrugViewModel.DeleteDrugById(_connStringDefault, id);
                return Json(new object[] { true });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }
    }
}

Kintal_Detanl/Views/Drug/DrugDetails.cshtml
@using Kintal_Detanl.Models;
@model DrugViewModel
@using Kendo.Mvc.UI;

@{
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
    ViewBag.Title = "Drug Details";
}


<style>
    .k-autocomplete, .k-block, .k-button-group .k-tool, .k-calendar th, .k-colorpicker .k-i-arrow-s, .k-content, .k-dropdown-wrap, .k-dropzone-active, .k-editable-area, .k-filter-row > th, .k-footer-template td, .k-grid td, .k-grid td.k-state-selected, .k-grid-content-locked, .k-grid-footer, .k-grid-footer-locked, .k-grid-footer-wrap, .k-grid-header, .k-grid-header-locked, .k-grid-header-wrap, .k-group, .k-group-footer td, .k-grouping-header, .k-grouping-header .k-group-indicator, .k-header, .k-input, .k-pager-refresh, .k-pager-wrap, .k-pager-wrap .k-link, .k-panel > .k-item > .k-link, .k-panelbar .k-content, .k-panelbar .k-panel, .k-panelbar > .k-item > .k-link, .k-separator, .k-slider-track, .k-splitbar, .k-state-default, .k-state-default .k-select, .k-state-disabled, .k-textbox, .k-textbox > input, .k-tiles, .k-toolbar, .k-tooltip, .k-treemap-tile, .k-upload-files, .k-widget {
        border: 0.5px solid #f3f3f3 !important;
        color: #495057 !important;
        opacity: 0.9;
    }

        .k-autocomplete.k-state-default .k-input, .k-combobox .k-state-default .k-input, .k-multiselect-wrap, .k-numeric-wrap.k-state-default .k-input, .k-picker-wrap.k-state-default .k-input, .k-progress-status-wrap, .k-slider-selection, .k-slider-track {
            box-shadow: unset !important;
        }

        .k-autocomplete .k-input, .k-dropdown-wrap .k-input, .k-numeric-wrap .k-input, .k-picker-wrap .k-input, .k-selectbox .k-input, .k-textbox > input {
            height: 40px;
        }

    .k-numeric-wrap .k-select {
        padding-top: 5px !important;
    }

    select.form-control, .select2-container--default select.select2-selection--single, .select2-container--default .select2-selection--single select.select2-search__field, select.typeahead, select.tt-query, select.tt-hint {
        color: #495057;
    }
</style>

@using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "frmDrugDetails" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="row" style="margin-top:-15px;">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Drug Details</h4>
                    <div class="form-block">
                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-12">@Html.TextBoxFor(m => m.DrugName, new { @class = "form-control", @placeholder = "Drug Name" })</div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-12">@Html.TextBoxFor(m => m.GenericName, new { @class = "form-control", @placeholder = "Generic Name" })</div>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Description", @rows = "3" }) @*<textarea class="form-control" placeholder="Address" rows="3"></textarea>*@
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="btn-outer">
                                <input type="button" onclick="SaveDrugData();" class="btn btn-primary" value="Save" />
                                <input type="button" onclick="OpenPage('@Url.Action("DrugList", "Drug")');" class="btn btn-light" value="Close" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

    @Html.HiddenFor(x => x.Id)
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
     $(function () {
         if ('@ViewBag.PageMode' == "view") {
             $("#frmDrugDetails :input").prop('disabled', 'disabled');
         }
    });

    function SaveDrugData() {
        if (ValidateCtrl()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("DrugDetails", "Drug")',
                data: $('#frmDrugDetails').serialize(),
                cache: false,
                success: function (data) {
                    if (data[0] == true) {
                        jAlert("Drug details saved successfully.", 'Information Dialog', function () {
                            window.location.href = '/Drug/DrugList';
                        });
                    }
                    else {
                        jAlert(data[1].toString(), 'Information Dialog');
                    }
                },
                error: function (error) {
                }
            });
        }
    }

    function ValidateCtrl() {
        try {
            if ($("#DrugName").val().trim() == "") {
                jAlert("Drug name can not be empty.", 'Information Dialog');
                return false;
            }
        } catch (err) {
            jAlert(err, 'Information Dialog');
            return false;
        }
        return true;
    }

</script>

Kintal_Detanl/Views/Drug/DrugList.cshtml
@using Kintal_Detanl.Models;
@using Kendo.Mvc.UI;
@*RegisterViewModel*@

@{
    ViewBag.Title = "Drug List";
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <h4 class="col-md-6 card-title">Drug List</h4>
                    <div class="col-md-6 align-right"><a href="@Url.Action("DrugDetails", "Drug")" style="margin-bottom: 10px;" class="btn btn-primary"><i class="typcn icon typcn-plus"></i> Add New Drug</a></div>
                </div>
                <div class="grid year-detail-table">
                    <div class="table-responsive">
                        @(Html.Kendo().Grid<DrugViewModel>()
                              .Name("gridDrug")
                              .Columns(columns =>
                              {
                                  //columns.Bound(x => x.SrNo).Title("Sr No").Width(40).Sortable(false).Filterable(false);
                                  columns.Bound(x => x.DrugName).Title("Drug Name").Width(150);
                                  columns.Bound(x => x.GenericName).Title("Generic Name").Width(150);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("DrugDetails", "Drug", new { id = "#=Id#",mode = "view" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-view-04.png") + "' alt='Edit Drug'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("DrugDetails", "Drug", new { id = "#=Id#",mode = "edit" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-02.png") + "' alt='Edit Drug'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='DeleteDrug(\"#=Id#\");'><img src='" + @Url.Content("~/Content/images/action-03.png") + "' alt='Delete Drug'></a></span>").Sortable(false).Filterable(false);
                                  //columns.Bound(x => x.LastTreatment).Title("Treatment Details").Width(300);
                              })
                              .Sortable()
                              .Scrollable(s => s.Virtual(true).Height("auto"))
                              .Resizable(resize => resize.Columns(true))
                              .Filterable()
                              .HtmlAttributes(new { style = "min-height: 700px !important;" })
                              .AutoBind(false)
                              .DataSource(dataSource => dataSource
                                  .Ajax()
                                  .PageSize(30)
                                  .Read(read => read.Action("BindDrugList", "Drug").Type(HttpVerbs.Post))
                                  .ServerOperation(false)
                               )
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var popup, dataTable;
    $(document).ready(function () {
        $("#gridDrug").data("kendoGrid").dataSource.page(1);
        //setTimeout(function () { $("#gridDrug").data("kendoGrid").dataSource.read(); }, 300);
    });


  function OpenPage(url) {
    location.href = url;
  }

  function DeleteDrug(id) {
    jConfirm("Are you sure you want to delete this Drug Details?", "Confirmation Dialog", function(r) {
      if(r) {
        $.ajax({
          type: "DELETE",
          url: '@Url.Action("DeleteDrug", "Drug")',
          data: { id: id },
          cache: false,
          dataType: 'json',
          error: function (jqXHR, exception) {
            jAlert(exception.toString());
          },
          success: function (data) {
            if (data[0] == true) {
                jAlert("Drug details deleted successfully.", 'Information Dialog', function () {
                    $('#gridDrug').data('kendoGrid').dataSource.read(); 
                    $('#gridDrug').data('kendoGrid').refresh();
              });
            }
            else {
              jAlert(data[1].toString(), 'Information Dialog');
            }
          }
        });
      }
    });
  }
</script>