Kintal_Detanl/Models/LabViewModel.cs
using MspCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Kintal_Detanl.Models
{
    public class LabViewModel
    {
        #region Properties
        public long Id { get; set; }
        public string LabName { get; set; }
        public string Description { get; set; }
        #endregion

        #region Methods
        public static List<DropDown> BindLabDropdownList(string constring)
        {
            DataTable dtLabs = GetLabListFromDB(constring);
            return DropDown.BindDropDownFromTable(dtLabs, "LabName", "Id");
        }

        private static DataTable GetLabListFromDB(string constring)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(constring))
            {
                string strSql = "wp_sp_GetLabs";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);

                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
            }

            return dtblResult;
        }
        #endregion

        #region Lab data layer
        public static LabViewModel InsertOrUpdateLabDetails(string conString, LabViewModel labModel)
        {
            using (SqlConnection cn = new SqlConnection(conString))
            {
                cn.Open();
                SqlCommand cmd = new SqlCommand("wp_sp_InsertUpdateLabMaster", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(labModel.Id));
                cmd.Parameters.AddWithValue("@LabName", SqlUtils.SetDbConformValueString(labModel.LabName));
                cmd.Parameters.AddWithValue("@Description", SqlUtils.SetDbConformValueString(labModel.Description));

                SqlParameter outputParamReturnedValue = cmd.Parameters.Add("@ReturnValue", SqlDbType.Int);
                outputParamReturnedValue.Direction = ParameterDirection.Output;
                cmd.ExecuteNonQuery();
                labModel.Id = !string.IsNullOrWhiteSpace(cmd.Parameters["@ReturnValue"].Value.ToString()) ? Convert.ToInt32(cmd.Parameters["@ReturnValue"].Value) : 0;
                cn.Close();
                return labModel;
            }
        }
        public static List<LabViewModel> GetLabs(string conString)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getLabMasterList";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                List<LabViewModel> res = BindLabsListFromDataTable(dtblResult);
                return (res != null && res.Count > 0) ? res : new List<LabViewModel>();
            }
        }
        public static LabViewModel GetLabById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getLabMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                LabViewModel res = BindLabFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? res : new LabViewModel();
            }
        }
        public static bool DeleteLabById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_DeleteLabMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                LabViewModel res = BindLabFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? true : false;
            }
        }
        #endregion

        #region Data Access
        private static List<LabViewModel> BindLabsListFromDataTable(DataTable dtLab)
        {
            List<LabViewModel> labList = null;

            if (dtLab != null && dtLab.Rows.Count > 0)
            {
                labList = new List<LabViewModel>();
                using (DataTableReader dataTableReader = new DataTableReader(dtLab))
                {
                    while (dataTableReader.Read())
                    {
                        LabViewModel labModel = new LabViewModel();
                        LoadLabObjectDataFromDataTableReader(dataTableReader, labModel);
                        labList.Add(labModel);
                    }
                }
            }

            return labList;
        }
        private static LabViewModel BindLabFromDataTable(DataTable dtLab)
        {
            LabViewModel lab = null;
            if (dtLab != null && dtLab.Rows.Count > 0)
            {
                lab = new LabViewModel();
                DataTableReader inputDataTableReader = SqlUtils.CreateReaderMoveToFirstRow(dtLab);
                LoadLabObjectDataFromDataTableReader(inputDataTableReader, lab);
            }

            return lab;
        }
        private static void LoadLabObjectDataFromDataTableReader(DataTableReader inputDataTableReader, LabViewModel labModel)
        {
            if (inputDataTableReader != null && inputDataTableReader.HasRows)
            {
                labModel.Id = SqlUtils.GetInt64("Id", inputDataTableReader);
                labModel.LabName = SqlUtils.GetString("LabName", inputDataTableReader);
                labModel.Description = SqlUtils.GetString("Description", inputDataTableReader);
            }
        }
        #endregion
    }
}

Kintal_Detanl/Controllers/LabController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kintal_Detanl.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Kintal_Detanl.Controllers
{
    public class LabController : Controller
    {
        #region Connection String Declarations

        private static readonly string _connStringDefault = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        #endregion

        // GET: Lab/Index
        public ActionResult LabList()
        {
            return View();
        }

        [HttpPost]
        public JsonResult BindLabList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(LabViewModel.GetLabs(_connStringDefault).ToDataSourceResult(request));
        }

        //GET: Lab/LabDetails/id
        public ActionResult LabDetails(int id = 0, string mode = "add")
        {
            ViewBag.PageMode = mode;
            var lab = new LabViewModel();
            if (id > 0)
            {
                lab = LabViewModel.GetLabById(_connStringDefault, id);
            }
            return View(lab);
        }

        //POST: Lab/LabDetails
        [HttpPost]
        public ActionResult LabDetails(LabViewModel labModel)
        {
            try
            {
                var result = new LabViewModel();
                if (labModel != null && !string.IsNullOrWhiteSpace(labModel.LabName))
                {
                    result = LabViewModel.InsertOrUpdateLabDetails(_connStringDefault.ToString(), labModel);
                }
                return Json(new object[] { true, result });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }

        //DELETE: Lab/id
        [HttpDelete]
        public JsonResult DeleteLab(int id)
        {
            try
            {
                LabViewModel.DeleteLabById(_connStringDefault, id);
                return Json(new object[] { true });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }
    }
}

Kintal_Detanl/Views/Lab/LabDetails.cshtml
@using Kintal_Detanl.Models;
@model LabViewModel
@using Kendo.Mvc.UI;

@{
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
    ViewBag.Title = "Lab Details";
}


<style>
    .k-autocomplete, .k-block, .k-button-group .k-tool, .k-calendar th, .k-colorpicker .k-i-arrow-s, .k-content, .k-dropdown-wrap, .k-dropzone-active, .k-editable-area, .k-filter-row > th, .k-footer-template td, .k-grid td, .k-grid td.k-state-selected, .k-grid-content-locked, .k-grid-footer, .k-grid-footer-locked, .k-grid-footer-wrap, .k-grid-header, .k-grid-header-locked, .k-grid-header-wrap, .k-group, .k-group-footer td, .k-grouping-header, .k-grouping-header .k-group-indicator, .k-header, .k-input, .k-pager-refresh, .k-pager-wrap, .k-pager-wrap .k-link, .k-panel > .k-item > .k-link, .k-panelbar .k-content, .k-panelbar .k-panel, .k-panelbar > .k-item > .k-link, .k-separator, .k-slider-track, .k-splitbar, .k-state-default, .k-state-default .k-select, .k-state-disabled, .k-textbox, .k-textbox > input, .k-tiles, .k-toolbar, .k-tooltip, .k-treemap-tile, .k-upload-files, .k-widget {
        border: 0.5px solid #f3f3f3 !important;
        color: #495057 !important;
        opacity: 0.9;
    }

        .k-autocomplete.k-state-default .k-input, .k-combobox .k-state-default .k-input, .k-multiselect-wrap, .k-numeric-wrap.k-state-default .k-input, .k-picker-wrap.k-state-default .k-input, .k-progress-status-wrap, .k-slider-selection, .k-slider-track {
            box-shadow: unset !important;
        }

        .k-autocomplete .k-input, .k-dropdown-wrap .k-input, .k-numeric-wrap .k-input, .k-picker-wrap .k-input, .k-selectbox .k-input, .k-textbox > input {
            height: 40px;
        }

    .k-numeric-wrap .k-select {
        padding-top: 5px !important;
    }

    select.form-control, .select2-container--default select.select2-selection--single, .select2-container--default .select2-selection--single select.select2-search__field, select.typeahead, select.tt-query, select.tt-hint {
        color: #495057;
    }
</style>

@using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "frmLabDetails" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="row" style="margin-top:-15px;">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Lab Details</h4>
                    <div class="form-block">
                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-12">@Html.TextBoxFor(m => m.LabName, new { @class = "form-control", @placeholder = "Lab Name" })</div>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Description", @rows = "3" }) @*<textarea class="form-control" placeholder="Address" rows="3"></textarea>*@
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="btn-outer">
                                <input type="button" onclick="SaveLabData();" class="btn btn-primary" value="Save" />
                                <input type="button" onclick="OpenPage('@Url.Action("LabList", "Lab")');" class="btn btn-light" value="Close" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

    @Html.HiddenFor(x => x.Id)
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
     $(function () {
         if ('@ViewBag.PageMode' == "view") {
             $("#frmLabDetails :input").prop('disabled', 'disabled');
         }
    });

    function SaveLabData() {
        if (ValidateCtrl()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("LabDetails", "Lab")',
                data: $('#frmLabDetails').serialize(),
                cache: false,
                success: function (data) {
                    if (data[0] == true) {
                        jAlert("Lab details saved successfully.", 'Information Dialog', function () {
                            window.location.href = '/Lab/LabList';
                        });
                    }
                    else {
                        jAlert(data[1].toString(), 'Information Dialog');
                    }
                },
                error: function (error) {
                }
            });
        }
    }

    function ValidateCtrl() {
        try {
            if ($("#LabName").val().trim() == "") {
                jAlert("Lab name can not be empty.", 'Information Dialog');
                return false;
            }
        } catch (err) {
            jAlert(err, 'Information Dialog');
            return false;
        }
        return true;
    }

</script>

Kintal_Detanl/Views/Lab/LabList.cshtml
@using Kintal_Detanl.Models;
@using Kendo.Mvc.UI;
@*RegisterViewModel*@

@{
    ViewBag.Title = "Lab List";
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <h4 class="col-md-6 card-title">Lab List</h4>
                    <div class="col-md-6 align-right"><a href="@Url.Action("LabDetails", "Lab")" style="margin-bottom: 10px;" class="btn btn-primary"><i class="typcn icon typcn-plus"></i> Add New Lab</a></div>
                </div>
                <div class="grid year-detail-table">
                    <div class="table-responsive">
                        @(Html.Kendo().Grid<LabViewModel>()
                              .Name("gridLab")
                              .Columns(columns =>
                              {
                                  //columns.Bound(x => x.SrNo).Title("Sr No").Width(40).Sortable(false).Filterable(false);
                                  columns.Bound(x => x.LabName).Title("Lab Name").Width(150);
                                  columns.Bound(x => x.Description).Title("Description").Width(150);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("LabDetails", "Lab", new { id = "#=Id#",mode = "view" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-view-04.png") + "' alt='Edit Lab'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("LabDetails", "Lab", new { id = "#=Id#",mode = "edit" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-02.png") + "' alt='Edit Lab'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='DeleteLab(\"#=Id#\");'><img src='" + @Url.Content("~/Content/images/action-03.png") + "' alt='Delete Lab'></a></span>").Sortable(false).Filterable(false);
                                  //columns.Bound(x => x.LastTreatment).Title("Treatment Details").Width(300);
                              })
                              .Sortable()
                              .Scrollable(s => s.Virtual(true).Height("auto"))
                              .Resizable(resize => resize.Columns(true))
                              .Filterable()
                              .HtmlAttributes(new { style = "min-height: 700px !important;" })
                              .AutoBind(false)
                              .DataSource(dataSource => dataSource
                                  .Ajax()
                                  .PageSize(30)
                                  .Read(read => read.Action("BindLabList", "Lab").Type(HttpVerbs.Post))
                                  .ServerOperation(false)
                               )
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var popup, dataTable;
    $(document).ready(function () {
        $("#gridLab").data("kendoGrid").dataSource.page(1);
        //setTimeout(function () { $("#gridLab").data("kendoGrid").dataSource.read(); }, 300);
    });


  function OpenPage(url) {
    location.href = url;
  }

  function DeleteLab(id) {
    jConfirm("Are you sure you want to delete this Lab Details?", "Confirmation Dialog", function(r) {
      if(r) {
        $.ajax({
          type: "DELETE",
          url: '@Url.Action("DeleteLab", "Lab")',
          data: { id: id },
          cache: false,
          dataType: 'json',
          error: function (jqXHR, exception) {
            jAlert(exception.toString());
          },
          success: function (data) {
            if (data[0] == true) {
                jAlert("Lab details deleted successfully.", 'Information Dialog', function () {
                    $('#gridLab').data('kendoGrid').dataSource.read(); 
                    $('#gridLab').data('kendoGrid').refresh();
              });
            }
            else {
              jAlert(data[1].toString(), 'Information Dialog');
            }
          }
        });
      }
    });
  }
</script>