Kintal_Detanl/Models/TestViewModel.cs
using Microsoft.Ajax.Utilities;
using MspCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Kintal_Detanl.Models
{
    public class TestViewModel
    {
        #region Properties
        public long Id { get; set; }
        public string TestName { get; set; }
        public string Description { get; set; }
        #endregion

        #region Test data layer
        public static TestViewModel InsertOrUpdateTestDetails(string conString, TestViewModel testModel)
        {
            using (SqlConnection cn = new SqlConnection(conString))
            {
                cn.Open();
                SqlCommand cmd = new SqlCommand("wp_sp_InsertUpdateTestMaster", cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(testModel.Id));
                cmd.Parameters.AddWithValue("@TestName", SqlUtils.SetDbConformValueString(testModel.TestName));
                cmd.Parameters.AddWithValue("@Description", SqlUtils.SetDbConformValueString(testModel.Description));

                SqlParameter outputParamReturnedValue = cmd.Parameters.Add("@ReturnValue", SqlDbType.Int);
                outputParamReturnedValue.Direction = ParameterDirection.Output;
                cmd.ExecuteNonQuery();
                testModel.Id = !string.IsNullOrWhiteSpace(cmd.Parameters["@ReturnValue"].Value.ToString()) ? Convert.ToInt32(cmd.Parameters["@ReturnValue"].Value) : 0;
                cn.Close();
                return testModel;
            }
        }
        public static List<TestViewModel> GetTests(string conString)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getTestMasterList";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                List<TestViewModel> res = BindTestsListFromDataTable(dtblResult);
                return (res != null && res.Count > 0) ? res : new List<TestViewModel>();
            }
        }
        public static TestViewModel GetTestById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_getTestMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                TestViewModel res = BindTestFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? res : new TestViewModel();
            }
        }
        public static bool DeleteTestById(string conString, long id)
        {
            DataTable dtblResult = null;
            using (SqlConnection cn = new SqlConnection(conString))
            {
                string strSql = "wp_sp_DeleteTestMasterById";
                SqlCommand cmd = new SqlCommand(strSql, cn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Id", SqlUtils.SetDbConformValueLong(id));
                SqlDataAdapter adpt = new SqlDataAdapter(cmd);
                cn.Open();
                dtblResult = new DataTable();
                adpt.Fill(dtblResult);
                TestViewModel res = BindTestFromDataTable(dtblResult);
                return (res != null && res.Id > 0) ? true : false;
            }
        }
        #endregion

        #region Data Access
        private static List<TestViewModel> BindTestsListFromDataTable(DataTable dtTest)
        {
            List<TestViewModel> testList = null;

            if (dtTest != null && dtTest.Rows.Count > 0)
            {
                testList = new List<TestViewModel>();
                using (DataTableReader dataTableReader = new DataTableReader(dtTest))
                {
                    while (dataTableReader.Read())
                    {
                        TestViewModel testModel = new TestViewModel();
                        LoadTestObjectDataFromDataTableReader(dataTableReader, testModel);
                        testList.Add(testModel);
                    }
                }
            }

            return testList;
        }
        private static TestViewModel BindTestFromDataTable(DataTable dtTest)
        {
            TestViewModel test = null;
            if (dtTest != null && dtTest.Rows.Count > 0)
            {
                test = new TestViewModel();
                DataTableReader inputDataTableReader = SqlUtils.CreateReaderMoveToFirstRow(dtTest);
                LoadTestObjectDataFromDataTableReader(inputDataTableReader, test);
            }

            return test;
        }
        private static void LoadTestObjectDataFromDataTableReader(DataTableReader inputDataTableReader, TestViewModel testModel)
        {
            if (inputDataTableReader != null && inputDataTableReader.HasRows)
            {
                testModel.Id = SqlUtils.GetInt64("Id", inputDataTableReader);
                testModel.TestName = SqlUtils.GetString("TestName", inputDataTableReader);
                testModel.Description = SqlUtils.GetString("Description", inputDataTableReader);
            }
        }
        #endregion
    }
}

Kintal_Detanl/Controllers/TestController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Kintal_Detanl.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Kintal_Detanl.Controllers
{
    public class TestController : Controller
    {
        #region Connection String Declarations

        private static readonly string _connStringDefault = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        #endregion

        // GET: Test/Index
        public ActionResult TestList()
        {
            return View();
        }

        [HttpPost]
        public JsonResult BindTestList([DataSourceRequest] DataSourceRequest request)
        {
            return Json(TestViewModel.GetTests(_connStringDefault).ToDataSourceResult(request));
        }

        //GET: Test/TestDetails/id
        public ActionResult TestDetails(int id = 0, string mode = "add")
        {
            ViewBag.PageMode = mode;
            var test = new TestViewModel();
            if (id > 0)
            {
                test = TestViewModel.GetTestById(_connStringDefault, id);
            }
            return View(test);
        }

        //POST: Test/TestDetails
        [HttpPost]
        public ActionResult TestDetails(TestViewModel testModel)
        {
            try
            {
                var result = new TestViewModel();
                if (testModel != null && !string.IsNullOrWhiteSpace(testModel.TestName))
                {
                    result = TestViewModel.InsertOrUpdateTestDetails(_connStringDefault.ToString(), testModel);
                }
                return Json(new object[] { true, result });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }

        //DELETE: Test/id
        [HttpDelete]
        public JsonResult DeleteTest(int id)
        {
            try
            {
                TestViewModel.DeleteTestById(_connStringDefault, id);
                return Json(new object[] { true });
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, ex.Message });
            }
        }
    }
}

Kintal_Detanl/Views/Test/TestDetails.cshtml
@using Kintal_Detanl.Models;
@model TestViewModel
@using Kendo.Mvc.UI;

@{
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
    ViewBag.Title = "Test Details";
}


<style>
    .k-autocomplete, .k-block, .k-button-group .k-tool, .k-calendar th, .k-colorpicker .k-i-arrow-s, .k-content, .k-dropdown-wrap, .k-dropzone-active, .k-editable-area, .k-filter-row > th, .k-footer-template td, .k-grid td, .k-grid td.k-state-selected, .k-grid-content-locked, .k-grid-footer, .k-grid-footer-locked, .k-grid-footer-wrap, .k-grid-header, .k-grid-header-locked, .k-grid-header-wrap, .k-group, .k-group-footer td, .k-grouping-header, .k-grouping-header .k-group-indicator, .k-header, .k-input, .k-pager-refresh, .k-pager-wrap, .k-pager-wrap .k-link, .k-panel > .k-item > .k-link, .k-panelbar .k-content, .k-panelbar .k-panel, .k-panelbar > .k-item > .k-link, .k-separator, .k-slider-track, .k-splitbar, .k-state-default, .k-state-default .k-select, .k-state-disabled, .k-textbox, .k-textbox > input, .k-tiles, .k-toolbar, .k-tooltip, .k-treemap-tile, .k-upload-files, .k-widget {
        border: 0.5px solid #f3f3f3 !important;
        color: #495057 !important;
        opacity: 0.9;
    }

        .k-autocomplete.k-state-default .k-input, .k-combobox .k-state-default .k-input, .k-multiselect-wrap, .k-numeric-wrap.k-state-default .k-input, .k-picker-wrap.k-state-default .k-input, .k-progress-status-wrap, .k-slider-selection, .k-slider-track {
            box-shadow: unset !important;
        }

        .k-autocomplete .k-input, .k-dropdown-wrap .k-input, .k-numeric-wrap .k-input, .k-picker-wrap .k-input, .k-selectbox .k-input, .k-textbox > input {
            height: 40px;
        }

    .k-numeric-wrap .k-select {
        padding-top: 5px !important;
    }

    select.form-control, .select2-container--default select.select2-selection--single, .select2-container--default .select2-selection--single select.select2-search__field, select.typeahead, select.tt-query, select.tt-hint {
        color: #495057;
    }
</style>

@using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "frmTestDetails" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="row" style="margin-top:-15px;">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Test Details</h4>
                    <div class="form-block">
                        <div class="row">

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-12">@Html.TextBoxFor(m => m.TestName, new { @class = "form-control", @placeholder = "Test Name" })</div>
                                </div>
                            </div>
                            @*<div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-12">@Html.TextBoxFor(m => m.GenericName, new { @class = "form-control", @placeholder = "Generic Name" })</div>
                                </div>
                            </div>*@

                            <div class="col-md-12">
                                <div class="form-group row">
                                    <div class="col-sm-12">
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Description", @rows = "3" }) @*<textarea class="form-control" placeholder="Address" rows="3"></textarea>*@
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="btn-outer">
                                <input type="button" onclick="SaveTestData();" class="btn btn-primary" value="Save" />
                                <input type="button" onclick="OpenPage('@Url.Action("TestList", "Test")');" class="btn btn-light" value="Close" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

    @Html.HiddenFor(x => x.Id)
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
     $(function () {
         if ('@ViewBag.PageMode' == "view") {
             $("#frmTestDetails :input").prop('disabled', 'disabled');
         }
    });

    function SaveTestData() {
        if (ValidateCtrl()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("TestDetails", "Test")',
                data: $('#frmTestDetails').serialize(),
                cache: false,
                success: function (data) {
                    if (data[0] == true) {
                        jAlert("Test details saved successfully.", 'Information Dialog', function () {
                            window.location.href = '/Test/TestList';
                        });
                    }
                    else {
                        jAlert(data[1].toString(), 'Information Dialog');
                    }
                },
                error: function (error) {
                }
            });
        }
    }

    function ValidateCtrl() {
        try {
            if ($("#TestName").val().trim() == "") {
                jAlert("Test name can not be empty.", 'Information Dialog');
                return false;
            }
        } catch (err) {
            jAlert(err, 'Information Dialog');
            return false;
        }
        return true;
    }

</script>

Kintal_Detanl/Views/Test/TestList.cshtml
@using Kintal_Detanl.Models;
@using Kendo.Mvc.UI;
@*RegisterViewModel*@

@{
    ViewBag.Title = "Test List";
    IEnumerable<string> dateFormats = new string[] { "yyyy", "d-M-yyyy", "d-MM-yyyy", "dd-MM-yyyy", "d-M-yy", "d-MM-yy", "dd-MM-yy", "dd-MM", "d/M/yyyy", "d/MM/yyyy", "dd/MM/yyyy", "d/MM/yy", "dd/MM/yy", "dd/MM", "d.M.yyyy", "d.MM.yyyy", "dd.MM.yyyy", "d.M.yy", "d.MM.yy", "dd.MM.yy", "dd.MM", "dd", "MMM", "MMMM" };
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <h4 class="col-md-6 card-title">Test List</h4>
                    <div class="col-md-6 align-right"><a href="@Url.Action("TestDetails", "Test")" style="margin-bottom: 10px;" class="btn btn-primary"><i class="typcn icon typcn-plus"></i> Add New Test</a></div>
                </div>
                <div class="grid year-detail-table">
                    <div class="table-responsive">
                        @(Html.Kendo().Grid<TestViewModel>()
                              .Name("gridTest")
                              .Columns(columns =>
                              {
                                  //columns.Bound(x => x.SrNo).Title("Sr No").Width(40).Sortable(false).Filterable(false);
                                  columns.Bound(x => x.TestName).Title("Test Name").Width(150);
                                  columns.Bound(x => x.Description).Title("Description").Width(150);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("TestDetails", "Test", new { id = "#=Id#",mode = "view" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-view-04.png") + "' alt='Edit Test'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='OpenPage(\"" + Url.Action("TestDetails", "Test", new { id = "#=Id#",mode = "edit" }) + "\");'><img src='" + @Url.Content("~/Content/images/action-02.png") + "' alt='Edit Test'></a></span>").Sortable(false).Filterable(false);
                                  columns.Bound(x => x.Id).Title("").Width(40).ClientTemplate("<span class='value'><a style='cursor: pointer;' onclick='DeleteTest(\"#=Id#\");'><img src='" + @Url.Content("~/Content/images/action-03.png") + "' alt='Delete Test'></a></span>").Sortable(false).Filterable(false);
                                  //columns.Bound(x => x.LastTreatment).Title("Treatment Details").Width(300);
                              })
                              .Sortable()
                              .Scrollable(s => s.Virtual(true).Height("auto"))
                              .Resizable(resize => resize.Columns(true))
                              .Filterable()
                              .HtmlAttributes(new { style = "min-height: 700px !important;" })
                              .AutoBind(false)
                              .DataSource(dataSource => dataSource
                                  .Ajax()
                                  .PageSize(30)
                                  .Read(read => read.Action("BindTestList", "Test").Type(HttpVerbs.Post))
                                  .ServerOperation(false)
                               )
                        )
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var popup, dataTable;
    $(document).ready(function () {
        $("#gridTest").data("kendoGrid").dataSource.page(1);
        //setTimeout(function () { $("#gridTest").data("kendoGrid").dataSource.read(); }, 300);
    });


    function OpenPage(url) {
        location.href = url;
    }

  function DeleteTest(id) {
    jConfirm("Are you sure you want to delete this Test Details?", "Confirmation Dialog", function(r) {
      if(r) {
        $.ajax({
          type: "DELETE",
          url: '@Url.Action("DeleteTest", "Test")',
          data: { id: id },
          cache: false,
          dataType: 'json',
          error: function (jqXHR, exception) {
            jAlert(exception.toString());
          },
          success: function (data) {
            if (data[0] == true) {
                jAlert("Test details deleted successfully.", 'Information Dialog', function () {
                    $('#gridTest').data('kendoGrid').dataSource.read(); 
                    $('#gridTest').data('kendoGrid').refresh();
              });
            }
            else {
              jAlert(data[1].toString(), 'Information Dialog');
            }
          }
        });
      }
    });
  }
</script>